---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=pxlapp.conf.j2 dest=/etc/init/pxlapp.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=pxlapp state=restarted
