---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - python-psycopg2
    - git

- name: Clone PXL Repository
  git: repo=https://github.com/PXL-CF2016/pxl-master-server.git dest={{ django_home }} force=yes
    version="ansible-deployment"

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ django_home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Get DB Password
  include_vars: secrets.yml


- name: Run Migrations
  environment:
    DB_NAME: "{{ DB_NAME }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_PORT : "{{ DB_PORT }}"
    SECRET_KEY: "{{ SECRET_KEY }}"
    NPR_KEY: "{{ NPR_KEY }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: pxl_master.settings
    command: migrate

- name: Collect Static Files
  environment:
    DB_NAME: "{{ DB_NAME }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_PORT : "{{ DB_PORT }}"
    SECRET_KEY: "{{ SECRET_KEY }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: pxl_master.settings
    command: collectstatic
